### ISSUE TITLE
Missing boost_system for fertilized_tests

### ISSUE THREAD

**Issue by rodrigob** [ChrislS/fertilized-forests#23] opened 2015-05-19 23:42 UTC
Under Ubuntu 14.04.2 LTS compilation fails at

```
g++ -o build/release/fertilized_tests/fertilized_tests -g -fopenmp -z origin -Wl,-rpath=\$ORIGIN build/release/fertilized_tests/DNNFeatureExtractor.o build/release/fertilized_tests/checks.o build/release/fertilized_tests/compute_feature_importances.o build/release/fertilized_tests/data_providers.o build/release/fertilized_tests/features.o build/release/fertilized_tests/forest.o build/release/fertilized_tests/gain.o build/release/fertilized_tests/impurities.o build/release/fertilized_tests/regression_calculator.o build/release/fertilized_tests/test.o build/release/fertilized_tests/test_template.o build/release/fertilized_tests/threshold_decider.o build/release/fertilized_tests/threshold_optimizer.o build/release/fertilized_tests/trees.o build/release/fertilized_tests/util.o -L. -lboost_unit_test_framework -lboost_serialization -lopencv_imgproc -lopencv_core -ltiff -lfreetype libfertilized.so

libfertilized.so: undefined reference to `boost::system::system_category()'
libfertilized.so: undefined reference to `boost::system::generic_category()'
```

because of a missing `-lboost_system`. I could not quickly find back where in the Scons file add the missing dependency.

**Comment by ChrislS** [comment] 2015-05-20 06:40
Hi Rodrigo,
I assume you built from the `stable` branch? The changes for version 1.01 (the submission for the ACM) are currently still in `unstable` and I want to merge them today. I still had a few colleagues giving me feedback on this, and hence it still wasn't merged. `unstable` is about 180 commits ahead and I think I fixed this issue there already.

**Comment by rodrigob** [comment] 2015-05-20 19:29
For information the unstable branch readme does not include the "manual compilation steps". I felt too uneasy to run `setup_environment.sh` while seeing that will play around with my python setup and ask for sudo.
Not seeing a compile.sh to try compilation by hand did not help either.
I see the point of having a "script that does it all", but I would suggest keeping instruction for when the script fails (because it will).

**Comment by rodrigob** [comment] 2015-05-20 19:30
On my machine unstable branch fails to compile with error

```
build/release/Presentation/C++/boosting.cpp: In function 'int main()':
build/release/Presentation/C++/boosting.cpp:91:27: error: 'struct fertilized::Soil<float, float, unsigned int, fertilized::Result_Types::probabilities>' has no member named 'Samme'
     auto algorithm = soil.Samme();
                           ^
build/release/Presentation/C++/boosting.cpp:92:26: error: 'struct fertilized::Soil<float, float, unsigned int, fertilized::Result_Types::probabilities>' has no member named 'BoostedTraining'
     auto training = soil.BoostedTraining(algorithm);
```

which looks like a plain C++ error.

**Comment by ChrislS** [comment] 2015-05-21 00:37
Ok, thank you for the feedback! I re-added default `compile.sh` and `compile.bat` scripts with standard options and explanations so that one has a fallback option if the setup script fails or one doesn't want to execute it (which I understand well enough). It was mainly thought as a convenience option, and it makes sense to keep it optional.

Glad that the missing linking issue is resolved on unstable. The C++ error is only there because you did not re-generate the interfaces after switching to unstable (the SAMME boosting has been added afterwards and is hence missing in the interface specification). Running `scons --generate-interfaces` and then doing the build should resolve it.

Thanks a lot for testing, I really appreciate it! :)

**Comment by rodrigob** [comment] 2015-05-21 05:56
So, after doing the `--generate-interfaces`, I get the same error than in the master branch

```
g++ -o build/release/fertilized_tests/fertilized_tests -g -fopenmp -z origin -Wl,-rpath=\$ORIGIN build/release/fertilized_tests/DNNFeatureExtractor.o build/release/fertilized_tests/boosting.o build/release/fertilized_tests/checks.o build/release/fertilized_tests/compute_feature_importances.o build/release/fertilized_tests/data_providers.o build/release/fertilized_tests/features.o build/release/fertilized_tests/forest.o build/release/fertilized_tests/gain.o build/release/fertilized_tests/impurities.o build/release/fertilized_tests/regression_calculator.o build/release/fertilized_tests/test.o build/release/fertilized_tests/test_template.o build/release/fertilized_tests/threshold_decider.o build/release/fertilized_tests/threshold_optimizer.o build/release/fertilized_tests/trees.o build/release/fertilized_tests/util.o -L. -lboost_unit_test_framework -lboost_serialization -lopencv_imgproc -lopencv_core -ltiff -lfreetype libfertilized.so
libfertilized.so: undefined reference to `boost::system::system_category()'
libfertilized.so: undefined reference to `boost::system::generic_category()'
collect2: error: ld returned 1 exit status
```

**Comment by ChrislS** [comment] 2015-05-21 09:54
Just tried to reproduce the issue and found out the following: this also has already been fixed, but the problem originated in a submodule. Just running `git submodule update --recursive` and rebuilding should work.

Sorry to bug you with these issues arising from having switched the branch. This should usually not occur and especially not with the automatic setup script, since it does this for you. Btw., I took your feedback serious and added a question before each call of `apt-get` in the script.

**Closed** 2015-06-02 11:46 UTC
