### ISSUE TITLE
scons: *** [build/release/fertilized/feature_extraction/feature_extraction.os] Error 1

### ISSUE THREAD

**Issue by deworrall92** [ChrislS/fertilized-forests#19] opened 2015-03-30 14:02 UTC
I'm getting the above error when trying to build fertilized forests with scons. I've followed the instructions to the letter and have made sure I have no issues with eigen, boost, etc. The config.log file doesn't seem to shed much light on the issue unfortunately. I include a few lines from my command line:

```
build/release/fertilized/feature_extraction/feature_extraction.cpp:68:73: note:   mismatched types 'std::_Deque_iterator<_Tp, _Tp&, _Tp*>' and 'uchar* {aka unsigned char*}'
                     resptr + i * image.getSize<0>() * image.getSize<1>());
                                                                         ^
scons: *** [build/release/fertilized/feature_extraction/feature_extraction.os] Error 1
scons: building terminated because of errors.
```

Cheers in advance

**Comment by ChrislS** [comment] 2015-03-30 14:15
Interesting! I assume, you are building from the current `master` branch. The command line makes me guess you are using gcc on a Linux system (please correct me if I'm wrong)? What version of the tools are you using? Which OpenCV version are you using (the line mentioned copies from a `cv::Mat`, so this might be relevant).

**Comment by deworrall92** [comment] 2015-03-30 14:39
Thanks for the fast reply. So I cloned from the master branch, and I am using gcc on a  Linux system (Ubuntu 14.04). I have versions of gcc and g++, 4.9.2; boost, 1.54.0; opencv 3.0.0; eigen3 3.2.0

**Comment by ChrislS** [comment] 2015-03-30 18:57
Ok, I had a look at it. I assume that this issue is related to OpenCV 3.0. The CI is using OpenCV 2.4, so I never ran into it.

I just pushed a potential patch to the unstable branch. You're very welcome to test it and to examine whether the problem persists. Don't worry about the 'failing' CI shields, the builds are triggered nightly and are currently not up-to-date. All builds and tests on `unstable` are passing for me.

If confirmed, I will merge the patch to master tomorrow.

**Comment by deworrall92** [comment] 2015-03-31 13:00
Thanks, it seems to progress further into the build now, but I think scons in now having issues with the fact that on my system when compiling with boost, I need to include -lboost_system with compile commands, i.e. link my system based boost library. I tried doing this manually, but my scons knowledge is very limited.

```
g++ -o build/release/fertilized_tests/fertilized_tests -g -fopenmp -z origin -Wl,-rpath=\$ORIGIN build/release/fertilized_tests/DNNFeatureExtractor.o build/release/fertilized_tests/boosting.o build/release/fertilized_tests/checks.o build/release/fertilized_tests/compute_feature_importances.o build/release/fertilized_tests/data_providers.o build/release/fertilized_tests/features.o build/release/fertilized_tests/forest.o build/release/fertilized_tests/gain.o build/release/fertilized_tests/impurities.o build/release/fertilized_tests/regression_calculator.o build/release/fertilized_tests/test.o build/release/fertilized_tests/test_template.o build/release/fertilized_tests/threshold_decider.o build/release/fertilized_tests/threshold_optimizer.o build/release/fertilized_tests/trees.o build/release/fertilized_tests/util.o -L/usr/include/boost -L. -lboost_unit_test_framework -lboost_serialization -lopencv_imgproc -lopencv_core -ltiff -lfreetype libfertilized.so
libfertilized.so: undefined reference to `boost::system::system_category()'
libfertilized.so: undefined reference to `boost::system::generic_category()'
collect2: error: ld returned 1 exit status
scons: *** [build/release/fertilized_tests/fertilized_tests] Error 1
scons: building terminated because of errors.
```

There doesn't happen to be a pip or conda version of fertilized forests, does there?

**Comment by ChrislS** [comment] 2015-03-31 16:01
Thanks for the comment. Indeed, boost test requires linking against boost system, and this was missing in the configuration files. I never ran into this issue, since I always built `--with-python`, in which case boost system is linked anyways. But this is fixed now on unstable. Sorry for the inconvenience! I'd be happy if you could confirm the solution. :)

There's no pip/conda version of the library yet, but I'm thinking of creating one.

**Comment by ChrislS** [comment] 2015-03-31 16:05
Since the change affects the SConsChecks submodule, either do a `git submodule update` after the pull or cd into SConsChecks and do a `git pull origin master` before building.

**Comment by deworrall92** [comment] 2015-04-01 10:19
Yes it installs. Thanks very much!

**Comment by ChrislS** [comment] 2015-04-01 12:30
Good to hear! :) Good luck with your projects and thanks for reporting and your feedback!

**Closed by ChrislS** 2015-04-01 12:30 UTC
